services:
  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  backend:
    build: backend/.
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      mongo:
        condition: service_started

  lobenonstairs:
    build: .
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      mongo:
        condition: service_started
      backend:
        condition: service_started

networks:
  default:
    driver: bridge