name: Docker Image Build and Push

on:

  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest



    steps:

      - id: getGitTag
        uses: little-core-labs/get-git-tag@v3.0.1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lobenonstairs:v1.0.0 # should be changed later
